---
deployment:
  tasks:
    - export DEPLOYPATH=/home/miagrone/ventas.miagronegocio.com
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH/.env
    - /bin/chmod 644 $DEPLOYPATH/.env
    - /bin/chmod -R 755 $DEPLOYPATH/storage
    - /bin/chmod -R 755 $DEPLOYPATH/bootstrap/cache
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache